"max_frames_number_per_cycle": 600
"bicep_poses_landmarks": [11,13,15,12,14,16,23,24,25,26,27,28]
"bicep_angles_landmarks" : [[11,13,15],[12,14,16],[13,11,23],[14,12,24]]
"lateral_raise_poses_landmarks": [11,13,15,12,14,16,23,24,25,26,27,28]
"lateral_raise_angles_landmarks" : [[11,13,15],[12,14,16],[13,11,23],[14,12,24]]
"available_evaluation_types" : ["poses","angles"]
"available_exercises" : ["bicep", "lateral_raise"]
"bicep_divider_landmarks" : [11,13,15]
"lateral_raise_divider_landmarks" : [23,11,13]
"min_detection_confidence" : 0.5
"min_tracking_confidence" : 0.5